package com.dhruv21.chromakit.core.model

import java.nio.ByteBuffer

/**
 * Represents the alpha/confidence mask generated by the segmentation engine.
 *
 * @param buffer Direct ByteBuffer containing mask alpha values (0.0 to 1.0 or single channel 0..255).
 * @param width Width of the mask.
 * @param height Height of the mask.
 * @param timestampNs Timestamp matching the source frame.
 */
data class ChromaMask(
    val buffer: ByteBuffer,
    val width: Int,
    val height: Int,
    val timestampNs: Long = System.nanoTime()
)
